// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: internal/storage/chunk/chunk.proto

package chunk

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DataRef with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DataRef) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DataRef with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in DataRefMultiError, or nil if none found.
func (m *DataRef) ValidateAll() error {
	return m.validate(true)
}

func (m *DataRef) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRef()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DataRefValidationError{
					field:  "Ref",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DataRefValidationError{
					field:  "Ref",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRef()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DataRefValidationError{
				field:  "Ref",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Hash

	// no validation rules for OffsetBytes

	// no validation rules for SizeBytes

	if len(errors) > 0 {
		return DataRefMultiError(errors)
	}

	return nil
}

// DataRefMultiError is an error wrapping multiple validation errors returned
// by DataRef.ValidateAll() if the designated constraints aren't met.
type DataRefMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DataRefMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DataRefMultiError) AllErrors() []error { return m }

// DataRefValidationError is the validation error returned by DataRef.Validate
// if the designated constraints aren't met.
type DataRefValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DataRefValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DataRefValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DataRefValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DataRefValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DataRefValidationError) ErrorName() string { return "DataRefValidationError" }

// Error satisfies the builtin error interface
func (e DataRefValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDataRef.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DataRefValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DataRefValidationError{}

// Validate checks the field values on Ref with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *Ref) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Ref with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in RefMultiError, or nil if none found.
func (m *Ref) ValidateAll() error {
	return m.validate(true)
}

func (m *Ref) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for SizeBytes

	// no validation rules for Edge

	// no validation rules for Dek

	// no validation rules for EncryptionAlgo

	// no validation rules for CompressionAlgo

	if len(errors) > 0 {
		return RefMultiError(errors)
	}

	return nil
}

// RefMultiError is an error wrapping multiple validation errors returned by
// Ref.ValidateAll() if the designated constraints aren't met.
type RefMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RefMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RefMultiError) AllErrors() []error { return m }

// RefValidationError is the validation error returned by Ref.Validate if the
// designated constraints aren't met.
type RefValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RefValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RefValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RefValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RefValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RefValidationError) ErrorName() string { return "RefValidationError" }

// Error satisfies the builtin error interface
func (e RefValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRef.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RefValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RefValidationError{}
